const { Configuration, OpenAIApi } = require("openai");
const fs = require('fs'); // for writing files
const path = require('path');

const dotenv = require('dotenv')
dotenv.config()

const key = process.env.OPENAI_API_KEY;

const configuration = new Configuration({
    apiKey: key,
});

const openai = new OpenAIApi(configuration);

const generateDALLEImage = async (prompt = 'banana', number = 1, size = 512) => {

    try {
        const response = await openai.createImage({
            prompt: prompt,
            n: number,
            size: `${size}x${size}`,
            response_format: 'b64_json'
        })
        console.log('image generated by DALLE');
        const b64 = response.data.data[0]['b64_json'];
        const buffer = Buffer.from(b64, 'base64');
        const filename = 'openAI_image.png';
        fs.writeFileSync(filename, buffer);

        const filePath = path.join(__dirname, filename);
        const data = fs.readFileSync(filePath);
        console.log('done writing file, file path: ', filePath)
        // send the file to the client
        return data;

    } catch (err) {
        console.log(err);
    }
}


//for writing files and saving to local
// generate_DALLE_Image('cookie shaped like a banana', 1, 256).then(
//     response =>{
//         console.log('saving file')
//         const now = new Date();
//         for(let i = 0; i< response.data.length; i++){
//             const b64 = response.data[i]['b64_json']; 
//             const buffer = Buffer.from(b64, 'base64');
//             const filename = `image_${i}.png`;
//             fs.writeFileSync(filename, buffer);

//         }
//         return filename;
//     }
// ).then( (filename) => {
//     console.log('done')
//     console.log(`./${filename}`) //res.data[0].b64_json
//     debugger
// })
// console.log(response.data.choices[0].text);
module.exports = { generateDALLEImage };