const { Configuration, OpenAIApi } = require("openai");
//const fs = require('fs'); // for writing files

const dotenv = require('dotenv')
dotenv.config()

const key = process.env.OPENAI_API_KEY;
console.log(key)

const configuration = new Configuration({
  apiKey: key,
});

const openai = new OpenAIApi(configuration);

const generate_DALLE_Image = async (prompt, number = 1, size = 512) =>{
    console.log('Inside generate_DALLE_Image');

    const response = await openai.createImage({
        prompt: prompt,
        n: number,
        size: `${size}x${size}`,
        //response_format: 'b64_json'
    })

    console.log('image generated by DALLE: ', response.data.data[0].url);
    return response.data;

}

module.exports = { generate_DALLE_Image };

// for writing files and saving to local
// predict().then(
//     response =>{
//         const now = new Date();
//         for(let i = 0; i< response.data.length; i++){
//             const b64 = response.data[i]['b64_json']; 
//             const buffer = Buffer.from(b64, 'base64');
//             const filename = `image_${now}_${i}.png`;
//             fs.writeFileSync(filename, buffer);

//         }
//     }
// )

// console.log(response.data.choices[0].text);