const { Configuration, OpenAIApi } = require("openai");
const fs = require('fs'); // for writing files
const aws = require('aws-sdk')
const path = require('path');

const dotenv = require('dotenv')
dotenv.config()

// const region = process.env.AWS_REGION;
// const bucketName = process.env.AWS_BUCKET;
// const accessKeyId = process.env.AWS_ACCESS_KEY;
// const secretAccessKey = process.env.AWS_SECRET_KEY;

// const s3 = new aws.S3({ 
//     region,
//     accessKeyId,
//     secretAccessKey,
//     signatureVersion: 'v4'
// })

const key = process.env.OPENAI_API_KEY;

const configuration = new Configuration({
    apiKey: key,
});

const openai = new OpenAIApi(configuration);

const generate_DALLE_Image = async (prompt = 'banana', number = 1, size = 512) => {

    try {
        const response = await openai.createImage({
            prompt: prompt,
            n: number,
            size: `${size}x${size}`,
            response_format: 'b64_json'
        })
        console.log('image generated by DALLE');
        // return response.data; //image data
        const b64 = response.data.data[0]['b64_json'];
        const buffer = Buffer.from(b64, 'base64');
        const filename = 'image_0.png';
        fs.writeFileSync(filename, buffer);
        

        const filePath = path.join(__dirname, 'image_0.png');
        const data = fs.readFileSync(filePath);
        console.log('done, file path: ', filePath)
        // send the file to the client
        return data;

        // const params = ({
        //     Bucket: bucketName,
        //     Key: fullPath,
        //     Expires: 60
        // })

        // const uploadURL = await s3.getSignedUrlPromise('putObject', params)
        // return uploadURL
    } catch (err) {
        console.log(err);
        return err;
    }
}


//for writing files and saving to local
// generate_DALLE_Image('cookie shaped like a banana', 1, 256).then(
//     response =>{
//         console.log('saving file')
//         const now = new Date();
//         for(let i = 0; i< response.data.length; i++){
//             const b64 = response.data[i]['b64_json']; 
//             const buffer = Buffer.from(b64, 'base64');
//             const filename = `image_${i}.png`;
//             fs.writeFileSync(filename, buffer);

//         }
//         return filename;
//     }
// ).then( (filename) => {
//     console.log('done')
//     console.log(`./${filename}`) //res.data[0].b64_json
//     debugger
// })
// console.log(response.data.choices[0].text);
module.exports = { generate_DALLE_Image };