const { Configuration, OpenAIApi } = require("openai");
const fs = require('fs'); 
const path = require('path');

const dotenv = require('dotenv')
dotenv.config()

const key = process.env.OPENAI_API_KEY;

const configuration = new Configuration({
    apiKey: key,
});

const openai = new OpenAIApi(configuration);

const generateOpenAIImage = async (prompt = 'banana', number = 1, size = 512) => {

    try {
        const response = await openai.createImage({
            prompt: prompt,
            n: number,
            size: `${size}x${size}`,
            response_format: 'b64_json'
        })
        console.log('image generated by DALLE');
        const b64 = response.data.data[0]['b64_json'];
        const buffer = Buffer.from(b64, 'base64');
        const filename = 'openAI_image.png';
        fs.writeFileSync(filename, buffer);

        const filePath = path.join(__dirname, filename);
        const data = fs.readFileSync(filePath);
        return data;

    } catch (err) {
        console.log('error in generateOpenAIImage: ', err);
        return err;
    }
}

module.exports = { generateOpenAIImage };