import {useState} from 'react';
import { apiURL } from "../../utils/apiURL"

function CreateImage() {
    const URL = apiURL();
    const [prompt, setPrompt] = useState('');
    const [image, setImage] = useState('');

    const generateImage = (e) => {
        e.preventDefault();
        const reqOptions = {
            method: 'POST',
            body: JSON.stringify({ prompt }),
            headers: { 'Content-Type': 'application/json', }
        }
        fetch(`${URL}/dalle`, reqOptions)
        .then(res => res.json())
            .then(data => {
                console.log('data: ', data)
                debugger
                setImage(data.data[0].url)

            }).catch(err => {
                console.log('catching error in generateImage in CreateImage')
                console.log(err)
            })
    }

    return (
        <form > 
            <input id='prompt' placeholder='prompt' maxLength="50" required onChange={(e) => setPrompt(e.target.value)} value={prompt} />
            <button onClick={e=>generateImage(e)}>Generate</button>
            {image ? <img src={image} alt="generated by DALLE" /> : null }
        </form>
    );
}

export default CreateImage;